# Section A: Numpy

This section is composed of 5 parts with a total of 30 marks. You will be given empty code cells and the expected output. The final submission will be this Jupyter notebook with the code filled in.

1. Reshaping matrices and performing mathematical operations (5 marks)
2. For loop and randomization (5 marks)
3. Stacking and basic statistics (5 marks)
4. Slicing (6 marks)
5. Filtering (9 marks)

## Import Libraries

In [ ]:
import numpy as np

### Q1. Reshaping matrices and performing mathematical operations (Total: 5 marks)

### numpy.arange

The definition of numpy.arange is given as such:

*numpy.arange([start, ]stop, [step, ]dtype=None)*

**1.1   Create a numpy array A containing the numbers 0 to 11 using arange(stop), and reshape it into a 4-by-3 matrix. Print it. (2 marks)**



array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

**1.2 Create a numpy array B starting from -2, ending at 8, at a step of 3, such that it contains the elements, -2, 1, 4 and 7. Print it. (1 mark)**

array([-2,  1,  4,  7])

**1.3 Reshape B such that it is has a shape of (1,4), overwriting the original variable. Print out the reshaped B. (1 mark)**

array([[-2,  1,  4,  7]])

**1.4 Performing a dot product of B and A in that order and print out the result. (1 mark)**

array([[ 90, 100, 110]])



---



### Q2. For loop and randomization (Total: 5 marks)

**Perform all the following steps:**

*   **Write a for loop using the form "for index in range(_):" to loop 8 times. (1 mark)**
*   **Create an array called "arr" in this loop using numpy.arange(start, stop) to create an array containing the numbers 1 to 6. (1 mark)**
*   **Use numpy.random to set a random seed to the remainder of index when divided by 4 in the loop. (2 marks)**
*   **Use numpy.random to shuffle the array "arr" (1 mark)**
*   **Print out the shuffled arrays.**


[6 3 2 4 1 5]
[3 2 5 1 4 6]
[5 2 4 3 6 1]
[4 6 5 2 1 3]
[6 3 2 4 1 5]
[3 2 5 1 4 6]
[5 2 4 3 6 1]
[4 6 5 2 1 3]


---

### Q3. Stacking and basic statistics (Total: 5 marks)

**3.1 Perform a column stack of the lists C, D and E, in that order, and assign the result of a variable called columnStack. Print out columnStack. (1 mark)**

In [ ]:
# Do NOT modify this cell.
# Just run the command as is.
# Defining 3 lists:
C = [-1,3,5]
D = [2,8,-3]
E = [7,9,4]

array([[-1,  2,  7],
       [ 3,  8,  9],
       [ 5, -3,  4]])

**3.2 Print out the mean of each column to 3 decimal places. (2 marks)**

array([2.333, 2.333, 6.667])

**Run the cell below as is.**

In [ ]:
# Do NOT modify this cell.
# Just run the command as is.
# Defining 2 matrices:
np.random.seed(631)
F = np.random.randint(low=3,high=70, size=(2,2))
print(F)
print()
np.random.seed(116)
G = np.random.randint(low=3,high=70, size=(2,2))
print(G)

[[28 23]
 [52  5]]

[[56 62]
 [52 49]]


**3.3 Stack matrices F and G horizontally using numpy.hstack(), and assign the result to a variable called F_then_G. Print out this variable. (1 mark)**

array([[28, 23, 56, 62],
       [52,  5, 52, 49]])

**3.4 Stack the *transpose of the matrix F* and the *transpose of the matrix G* vertically using numpy.concatenate(), and assign the result to a variable called FT_on_GT. Print out this variable. (1 mark)**

array([[28, 52],
       [23,  5],
       [56, 52],
       [62, 49]])

---

### Q4. Slicing (Total: 6 marks)

**Run the cell below as is.**

In [ ]:
# Do NOT modify this cell.
# Just run the command as is.
# Defining 1 matrix:
np.random.seed(7341)
H = np.random.randint(low=-10,high=60, size=(4,4))
print(H)

[[15 -2  2 27]
 [23 26 -6 36]
 [14 34  8 56]
 [38 14 41 29]]


**4.1 Slice the last 3 rows and second to third column of H and assign the subset to a variable H_slice1. (1 mark)**

array([[26, -6],
       [34,  8],
       [14, 41]])

**4.2 Change the element at the 2nd row, 3rd column of H to the cube of its current value using the power operator of Python. (1 mark)**

array([[  15,   -2,    2,   27],
       [  23,   26, -216,   36],
       [  14,   34,    8,   56],
       [  38,   14,   41,   29]])

**4.3 The first 3 columns of H are features for machine learning, while the last column of H is the label. Using only ":" and negative numbers for slicing with any possible reshaping, print out the features and label as 2-dimensional matrices. (2 marks)**

[[  15   -2    2]
 [  23   26 -216]
 [  14   34    8]
 [  38   14   41]]

[[27]
 [36]
 [56]
 [29]]


**4.4 You are required to select the following cells from matrix H (zero-index based):**

* **row 3, column 0**
* **row 1, column 2**
* **row 2, column 2**
* **row 1, column 3**

**Create a numpy array "row_indices" to store the row indices, and a numpy array "col_indices" to store the column indices. Print them out.**

**(1 mark)**

[3 1 2 1]

[0 2 2 3]


**4.5 Use row_indices and col_indices to select the required elements from H. (1 mark)**

array([  38, -216,    8,   36])

---

### Q5. Filtering (Total: 9 marks)

**Run the cell below as is.**

In [ ]:
# Do NOT modify this cell.
# Just run the command as is.
# Defining 1 list:
I = np.array([[-7,3],[6,15],[-14,2]])
I

array([[ -7,   3],
       [  6,  15],
       [-14,   2]])

**5.1 Create a filter "filter1" that is True if an element in I is negative, and False otherwise. Use filter1 to filter out the negative elements in I. (1 mark)**

array([ -7, -14])

**5.2 In a single line of code, filter out the even numbers in I. (1 mark)**

array([  6, -14,   2])

**5.3 In a single line of code, add 100 to the multiples of 7 in I. In another line of code, print I out. (1 mark)**

array([[93,  3],
       [ 6, 15],
       [86,  2]])

**Run the cell below as is.**

In [ ]:
# Do NOT modify this cell.
# Just run the command as is.
# Defining 2 lists:
J = np.array([5,-3,2,-1,4])
K = np.array([11,9,-7,23,29])

**5.4 Create a filter called "filter2" that is a numpy array containing just Boolean values to select (using numpy.where()) the first element of J, then the 2nd, 3rd and 4th elements of K, then finally the last element of J. Print the output. (2 marks)**

[ 5  9 -7 23  4]


**5.5 Set a random seed of 1890, and use numpy.random.rand() to create a 4-by-4 matrix, assigning the result to a variable named "L". Print L out. (1 mark)**

array([[0.44 , 0.502, 0.696, 0.573],
       [0.971, 0.423, 0.801, 0.044],
       [0.677, 0.428, 0.239, 0.882],
       [0.413, 0.248, 0.619, 0.893]])

**5.6 Using numpy.where() on L, create a matrix that holds 1 in a cell if the corresponding cell is above 0.75, 0 otherwise, storing the result in L_3quarters. Print out L_3quarters. (1 mark)**

array([[0, 0, 0, 0],
       [1, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 1]])

**5.7 Using numpy.unique(), with the return_counts attribute set to True, find out the number of unique numbers in L_3quarters. Use dict and zip to create a dictionary that contains the count of 0 and 1 in L_3quarters. (2 marks)**

{0: 12, 1: 4}

# END OF SECTION A